config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users

  resources :users, only: [:show, :edit, :update, :index]
  resources :books


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  validates :title, presence: true, length: {maximum: 200}
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attachment :profile_image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy

  def email_required?
    false
  end

  def email_change?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys:[:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}

  def ensure_correct_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      render ("books/index")
    end
  end

  def index
    @current_user = current_user
    @books = Book.all.order(created_at: :desc)
    @book = Book.new
  end

  def show
    @book = Book.new
    @book_select = Book.find(params[:id])
    @current_user = current_user
    @user = @book_select.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have update book successfully."
      redirect_to book_path(@book)
    else
      render ("books/edit")
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only: [:edit, :update]}

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] ="You have update user successfully."
      redirect_to user_path(current_user)
    else
      render("users/edit")
    end
  end

  def index
    @users = User.all
    @current_user = current_user
    @book = Book.new
  end

  private
    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <h1 style="font-size: 36px;">Editing Book</h1>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li style="color: red;">error <%= message %></li>
    <% end %>
    </ul>
    <div class="form-body">
      <%= form_for(@book) do |f| %>
        <div class="field row" style="margin-bottom: 10px;">
          <label>Title</label>
          <%= f.text_field :title, class: "col-xs-12" %>
        </div>

        <div class="field row" style="margin-bottom: 10px;">
          <label>Opinion</label>
          <%= f.text_area :body, class: "col-xs-12" %>
        </div>

        <div class="action row">
          <%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %>
      <span>|</span>
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="error_expansion">
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li style="color: red;">error <%= message %></li>
    <% end %>
  </ul>
</div>

<div class="row">
  <div class="col-lg-3">
    <%= render 'users/sidebar', user: @current_user, book: @book %>
  </div>

  <div class="col-lg-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: 'no_image.jpg', size: "40x40" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<!-- sidebar -->
<div class="row">
  <div class="col-lg-3">
    <h2>User info</h2>
<div class="sidebar">
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: 'no_image.jpg' %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
      <%= link_to edit_user_path(@user), class: "btn btn-default col-xs-12" do %>
      <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
      <% end %>
  </div>


  <div class="col-lg-9">
    <h2>Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(@book_select.user) do %>
            <%= attachment_image_tag @book_select.user, :profile_image, format: 'jpeg', fallback: 'no_image.jpg', size: "40x40" %><br>
            <%= @book_select.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book_select.id) do %>
              <%= @book_select.title %>
            <% end %>
          </td>
          <td>
            <%= @book_select.body %>
          </td>
          <% if @book_select.user_id == current_user.id %>
            <td>
              <%= link_to edit_book_path(@book_select), class: " btn-sm btn btn-success" do %>
                Edit
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book_select), class: "btn-sm btn btn-danger", method: :delete do %>
                Destroy
              <% end %>
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/homes/about.html.erb
<h1>
  Welcome to
  <strong><span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers</strong>!
</h1>

app/views/homes/top.html.erb
<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>
      <strong>
      Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers
      </strong>&emsp;‼︎
    </h1>

    <p>In <strong>
      <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,</strong>
    </p>
    <p>you can share and exchange your opinions, inpressions, and emotions<br>
    about varioius books!
    </p>

    <%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %>
    <br>
    <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <!-- header -->
    <header class="navbar navbar-fixed-top navbar-inverse" style="background-color: #000;">
      <div class="container">
        <nav class="nav navbar-nav navbar-left" style="color: #fff; font-size: 20px;">
          <span>Bookers</span>
        </nav>
        <!-- header-right-mene -->
        <nav>
          <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animation="zoomIn fadeIn fadeInUp fadeIn">
            <% if user_signed_in? %>
              <li class="">
                <%= link_to user_path(current_user) do %>
                  <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home
                <% end %>
              </li>
              <li class="">
                <%= link_to users_path do %>
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Users
                <% end %>
              </li>
              <li class="">
                <%= link_to books_path do %>
                  <span class="glyphicon glyphicon-book" aria-hidden="true"></span> Books
                <% end %>
              </li>
              <li class="">
                <%= link_to destroy_user_session_path, method: :delete do %>
                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> logout
                <% end %>
              </li>

            <% else %>
              <li class="">
                <%= link_to root_path do %>
                  <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home
                <% end %>
              </li>
              <li class="">
                <%= link_to home_about_path do %>
                  <span class="glyphicon glyphicon-link" aria-hidden="true"></span> About
                <% end %>
              </li>
              <li class="">
                <%= link_to new_user_registration_path do %>
                  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> sign up
                <% end %>
              </li>
              <li class="">
                <%= link_to new_user_session_path do %>
                  <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> login
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
      <!-- header -->
    <div class="body" style="margin-top: 50px;">
      <div class="container">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
      <%= yield %>
      </div>
    </div>
  <!-- footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.Inc</p>
          </div>
        </div>
      </div>
    </footer>
  <!-- footer -->
    </div>
  </body>
</html>

app/views/users/_sidebar.html.erb
<h2>User info</h2>
<div class="sidebar">
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: 'no_image.jpg' %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
      <%= link_to edit_user_path(current_user), class: "btn btn-default col-xs-12" do %>
      <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
      <% end %>
  </div>

  <h2>New book</h2>
  <%= form_for (@book) do |f| %>
    <div class="row">
      <h4>Title</h4>
      <%= f.text_field :title, class: "col-xs-12" %>
    </div>
    <div class="row">
      <h4>Opinion</h4>
      <%= f.text_area :body, class: "col-xs-12"%>
    </div>
    <br>
    <div class="row">
      <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>
<div class="error_expansion">
    <% @user.errors.full_messages.each do |message| %>
        <li style="color: red;">error <%= message %></li>
    <% end %>
</div>
<div class="form-body">
  <%= form_for(@user) do |f| %>
    <h4>Name</h4>
    <%= f.text_field :name %>

    <h4>Image</h4>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>

    <h4>Introduction</h4>
    <%= f.text_area :introduction %><br>
    <%= f.submit "Update User", class: "btn btn-default"  %>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-lg-3">
    <%= render 'users/sidebar', user: @current_user, book: @book %>
  </div>

  <div class="col-lg-9">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: 'no_image.jpg', size: "40x40" %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "show", user_path(user.id) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<!-- sidebar -->
<div class="row">
  <div class="col-lg-3">
    <h2>User info</h2>
<div class="sidebar">
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: 'no_image.jpg' %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
      <%= link_to edit_user_path(@user), class: "btn btn-default col-xs-12" do %>
      <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
      <% end %>
  </div>

  <h2>New book</h2>
  <%= form_for (@book) do |f| %>
    <div class="row">
      <h4>Title</h4>
      <%= f.text_field :title, class: "col-xs-12" %>
    </div>
    <div class="row">
      <h4>Opinion</h4>
      <%= f.text_area :body, class: "col-xs-12"%>
    </div>
    <br>
    <div class="row">
      <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
    </div>
  <% end %>
</div>
  </div>
<!-- sidebar -->
  <div class="col-lg-9">
    <h2>Books</h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: 'no_image.jpg', size: "40x40" %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
        <% end %>
      </thead>
    </table>
  </div>
</div>